In [61]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [62]:
df= pd.read_csv('Training.csv')

In [63]:
df

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  scurring  skin_peeling  silver_like_dusting  small_dents_in_nails  \
0     ...         0             0                    0                     0   
1     ...         0             0                    0                     0   
2     ...         0             0                    0                     0   
3     ...         0             0                    0                     0   
4     ...         0             0                    0                     0   
...   ...       ...           ...                  ...                   ...   
4915  ...         0             0                    0                     0   
4916  ...         1             0                    0                     0   
4917  ...         0             0                    0                     0   
4918  ...         0             1                    1                     1   
4919  ...         0             0                    0                     0   

      inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                      0        0                     0                  0   
1                      0        0                     0                  0   
2                      0        0                     0                  0   
3                      0        0                     0                  0   
4                      0        0                     0                  0   
...                  ...      ...                   ...                ...   
4915                   0        0                     0                  0   
4916                   0        0                     0                  0   
4917                   0        0                     0                  0   
4918                   1        0                     0                  0   
4919                   0        1                     1                  1   

                                    prognosis  Unnamed: 133  
0                            Fungal infection           NaN  
1                            Fungal infection           NaN  
2                            Fungal infection           NaN  
3                            Fungal infection 

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 134 entries, itching to Unnamed: 133
dtypes: float64(1), int64(132), object(1)
memory usage: 5.0+ MB


In [65]:
print(list(df.columns))

['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bow

In [66]:
df.drop(columns='Unnamed: 133',inplace=True)

In [67]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [68]:
arr=df['prognosis'].unique()
print(np.where(arr=='Fungal infection'))

(array([0], dtype=int64),)


In [69]:
def encode(t):
    return np.where(arr==t)[0][0]

df['prognosis_encode']=df['prognosis'].apply(encode)

In [70]:
""" test_df=pd.read_csv('Testing.csv')
test_df['prognosis_encode']=test_df.apply(encode)
test_df.head() """

" test_df=pd.read_csv('Testing.csv')\ntest_df['prognosis_encode']=test_df.apply(encode)\ntest_df.head() "

In [71]:
from sklearn.model_selection import train_test_split
df=pd.read_csv('Training.csv')
""" test_df=pd.read_csv('Testing.csv')
fr=[df,test_df]

final_df=pd.concat(fr,join='outer')
final_df.drop(columns=['Unnamed: 133'],inplace=True)
final_df """
df.drop(columns=['Unnamed: 133'],inplace=True)
""" df['prognosis_encode']=df['prognosis'].apply(encode) """

" df['prognosis_encode']=df['prognosis'].apply(encode) "

In [72]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['prognosis']),np.array(df['prognosis']), test_size=0.3,random_state=121)
print(X_train)

      itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
981         0          1                     0                    0   
3564        0          0                     0                    0   
4526        1          1                     0                    0   
4447        0          0                     0                    0   
4553        0          0                     0                    0   
...       ...        ...                   ...                  ...   
2113        0          0                     0                    0   
3572        0          0                     0                    0   
1631        0          1                     0                    0   
4565        1          0                     0                    0   
3394        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
981           0       0           0             0        0         

In [73]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier 
#svm = SVC()

In [74]:
#svm.fit(X_train,y_train)

In [75]:
#pred=svm.predict(X_test)
lg=RandomForestClassifier()
lg.fit(X_train,y_train)
pred=lg.predict(X_test)
print(pred[:10])
print(y_test[:10])

['Migraine' 'Hepatitis C' 'Hyperthyroidism' 'Urinary tract infection'
 'Gastroenteritis' 'Gastroenteritis' 'Chicken pox' 'Malaria'
 'Varicose veins' 'Typhoid']
['Migraine' 'Hepatitis C' 'Hyperthyroidism' 'Urinary tract infection'
 'Gastroenteritis' 'Gastroenteritis' 'Chicken pox' 'Malaria'
 'Varicose veins' 'Typhoid']


In [76]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [77]:
print(confusion_matrix(y_test,pred),classification_report(y_test,pred))
train_pred=lg.predict(X_train)
print(accuracy_score(y_train,train_pred))

[[41  0  0 ...  0  0  0]
 [ 0 32  0 ...  0  0  0]
 [ 0  0 32 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 27  0]
 [ 0  0  0 ...  0  0 40]]                                          precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        41
                                   AIDS       1.00      1.00      1.00        32
                                   Acne       1.00      1.00      1.00        32
                    Alcoholic hepatitis       1.00      1.00      1.00        43
                                Allergy       1.00      1.00      1.00        37
                              Arthritis       1.00      1.00      1.00        32
                       Bronchial Asthma       1.00      1.00      1.00        28
                   Cervical spondylosis       1.00      1.00      1.00        37
                            Chicken pox       1.00      1.00      1.00        35
                    Chronic chole

In [78]:
import pickle
pickle.dump(lg,open('model.pkl','wb')) 

In [79]:
list(df.columns)[:31]

['itching',
 'skin_rash',
 'nodal_skin_eruptions',
 'continuous_sneezing',
 'shivering',
 'chills',
 'joint_pain',
 'stomach_pain',
 'acidity',
 'ulcers_on_tongue',
 'muscle_wasting',
 'vomiting',
 'burning_micturition',
 'spotting_ urination',
 'fatigue',
 'weight_gain',
 'anxiety',
 'cold_hands_and_feets',
 'mood_swings',
 'weight_loss',
 'restlessness',
 'lethargy',
 'patches_in_throat',
 'irregular_sugar_level',
 'cough',
 'high_fever',
 'sunken_eyes',
 'breathlessness',
 'sweating',
 'dehydration',
 'indigestion']

In [80]:
symptoms = [
     'Cough', 'Fatigue', 'Headache', 'Nausea', 'Vomiting',
     'Shortness of breath', 'Chest pain', 'Sore throat', 'Runny nose', 'Sneezing', 'Watery eyes',
    'Swollen lymph nodes', 'Dizziness', 'Weakness', 'Chills', 'Sweating', 'Weight loss', 'Loss of appetite',
    'Constipation', 'Frequent urination', 'Difficulty sleeping', 'Anxiety', 'Depression', 'Skin itching'
]
a=[]
for i in symptoms:
    print(i)
    a.append(list(df.columns).index(i.lower()))
a

Cough
Fatigue
Headache
Nausea
Vomiting
Shortness of breath


ValueError: 'shortness of breath' is not in list